//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifeiWebService.SifeiWebServiceDev {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MApeados/")]
    public partial class SifeiException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string errorField;
        
        private string messageField;
        
        private byte[] xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MApeados/")]
    public partial class SOAPException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MApeados/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MApeados/", ConfigurationName="SifeiWebServiceDev.SIFEI")]
    public interface SIFEI {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/CambiaPasswordRequest", ReplyAction="http://MApeados/SIFEI/CambiaPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/CambiaPassword/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse CambiaPassword(SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/CambiaPasswordRequest", ReplyAction="http://MApeados/SIFEI/CambiaPasswordResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse> CambiaPasswordAsync(SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIAndURLRequest", ReplyAction="http://MApeados/SIFEI/getCFDIAndURLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getCFDIAndURL/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SOAPException), Action="http://MApeados/SIFEI/getCFDIAndURL/Fault/SOAPException", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse getCFDIAndURL(SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIAndURLRequest", ReplyAction="http://MApeados/SIFEI/getCFDIAndURLResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse> getCFDIAndURLAsync(SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIRequest", ReplyAction="http://MApeados/SIFEI/getCFDIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getCFDI/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SOAPException), Action="http://MApeados/SIFEI/getCFDI/Fault/SOAPException", Name="SOAPException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.IOException), Action="http://MApeados/SIFEI/getCFDI/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getCFDIResponse getCFDI(SifeiWebService.SifeiWebServiceDev.getCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIRequest", ReplyAction="http://MApeados/SIFEI/getCFDIResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIResponse> getCFDIAsync(SifeiWebService.SifeiWebServiceDev.getCFDIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDISendPDFRequest", ReplyAction="http://MApeados/SIFEI/getCFDISendPDFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getCFDISendPDF/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse getCFDISendPDF(SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDISendPDFRequest", ReplyAction="http://MApeados/SIFEI/getCFDISendPDFResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse> getCFDISendPDFAsync(SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIProcesaRequest", ReplyAction="http://MApeados/SIFEI/getCFDIProcesaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getCFDIProcesa/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse getCFDIProcesa(SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDIProcesaRequest", ReplyAction="http://MApeados/SIFEI/getCFDIProcesaResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse> getCFDIProcesaAsync(SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDISignRequest", ReplyAction="http://MApeados/SIFEI/getCFDISignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getCFDISign/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getCFDISignResponse getCFDISign(SifeiWebService.SifeiWebServiceDev.getCFDISignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getCFDISignRequest", ReplyAction="http://MApeados/SIFEI/getCFDISignResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISignResponse> getCFDISignAsync(SifeiWebService.SifeiWebServiceDev.getCFDISignRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/setCFDIRequest", ReplyAction="http://MApeados/SIFEI/setCFDIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/setCFDI/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.setCFDIResponse setCFDI(SifeiWebService.SifeiWebServiceDev.setCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/setCFDIRequest", ReplyAction="http://MApeados/SIFEI/setCFDIResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.setCFDIResponse> setCFDIAsync(SifeiWebService.SifeiWebServiceDev.setCFDIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getTimbreCFDIRequest", ReplyAction="http://MApeados/SIFEI/getTimbreCFDIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getTimbreCFDI/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse getTimbreCFDI(SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getTimbreCFDIRequest", ReplyAction="http://MApeados/SIFEI/getTimbreCFDIResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse> getTimbreCFDIAsync(SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getXMLRequest", ReplyAction="http://MApeados/SIFEI/getXMLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getXML/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getXMLResponse getXML(SifeiWebService.SifeiWebServiceDev.getXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getXMLRequest", ReplyAction="http://MApeados/SIFEI/getXMLResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLResponse> getXMLAsync(SifeiWebService.SifeiWebServiceDev.getXMLRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDIRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/cancelaCFDI/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse cancelaCFDI(SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDIRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDIResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse> cancelaCFDIAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDISectorPrimarioRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDISectorPrimarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/cancelaCFDISectorPrimario/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse cancelaCFDISectorPrimario(SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDISectorPrimarioRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDISectorPrimarioResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse> cancelaCFDISectorPrimarioAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDISignatureRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDISignatureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/cancelaCFDISignature/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse cancelaCFDISignature(SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/cancelaCFDISignatureRequest", ReplyAction="http://MApeados/SIFEI/cancelaCFDISignatureResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse> cancelaCFDISignatureAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getXMLProcesoRequest", ReplyAction="http://MApeados/SIFEI/getXMLProcesoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SifeiWebService.SifeiWebServiceDev.SifeiException), Action="http://MApeados/SIFEI/getXMLProceso/Fault/SifeiException", Name="SifeiException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse getXMLProceso(SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MApeados/SIFEI/getXMLProcesoRequest", ReplyAction="http://MApeados/SIFEI/getXMLProcesoResponse")]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse> getXMLProcesoAsync(SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiaPassword", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class CambiaPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewPassword;
        
        public CambiaPasswordRequest() {
        }
        
        public CambiaPasswordRequest(string Usuario, string Password, string NewPassword) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiaPasswordResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class CambiaPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public CambiaPasswordResponse() {
        }
        
        public CambiaPasswordResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDIAndURL", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIAndURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getCFDIAndURLRequest() {
        }
        
        public getCFDIAndURLRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDIAndURLResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIAndURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getCFDIAndURLResponse() {
        }
        
        public getCFDIAndURLResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDI", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getCFDIRequest() {
        }
        
        public getCFDIRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDIResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getCFDIResponse() {
        }
        
        public getCFDIResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDISendPDF", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDISendPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getCFDISendPDFRequest() {
        }
        
        public getCFDISendPDFRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDISendPDFResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDISendPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getCFDISendPDFResponse() {
        }
        
        public getCFDISendPDFResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDIProcesa", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIProcesaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getCFDIProcesaRequest() {
        }
        
        public getCFDIProcesaRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDIProcesaResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDIProcesaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getCFDIProcesaResponse() {
        }
        
        public getCFDIProcesaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDISign", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDISignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getCFDISignRequest() {
        }
        
        public getCFDISignRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCFDISignResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getCFDISignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getCFDISignResponse() {
        }
        
        public getCFDISignResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCFDI", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class setCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public setCFDIRequest() {
        }
        
        public setCFDIRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCFDIResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class setCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public setCFDIResponse() {
        }
        
        public setCFDIResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCFDI", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getTimbreCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoXMLZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdEquipo;
        
        public getTimbreCFDIRequest() {
        }
        
        public getTimbreCFDIRequest(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            this.Usuario = Usuario;
            this.Password = Password;
            this.archivoXMLZip = archivoXMLZip;
            this.Serie = Serie;
            this.IdEquipo = IdEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCFDIResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getTimbreCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getTimbreCFDIResponse() {
        }
        
        public getTimbreCFDIResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXML", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hash;
        
        public getXMLRequest() {
        }
        
        public getXMLRequest(string rfc, string pass, string hash) {
            this.rfc = rfc;
            this.pass = pass;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getXMLResponse() {
        }
        
        public getXMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDI", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioSIFEI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passPFX;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] UUIDS;
        
        public cancelaCFDIRequest() {
        }
        
        public cancelaCFDIRequest(string usuarioSIFEI, string passUser, string rfc, byte[] pfx, string passPFX, string[] UUIDS) {
            this.usuarioSIFEI = usuarioSIFEI;
            this.passUser = passUser;
            this.rfc = rfc;
            this.pfx = pfx;
            this.passPFX = passPFX;
            this.UUIDS = UUIDS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelaCFDIResponse() {
        }
        
        public cancelaCFDIResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDISectorPrimario", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDISectorPrimarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioSIFEI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] UUIDS;
        
        public cancelaCFDISectorPrimarioRequest() {
        }
        
        public cancelaCFDISectorPrimarioRequest(string usuarioSIFEI, string passUser, string rfc, string[] UUIDS) {
            this.usuarioSIFEI = usuarioSIFEI;
            this.passUser = passUser;
            this.rfc = rfc;
            this.UUIDS = UUIDS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDISectorPrimarioResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDISectorPrimarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelaCFDISectorPrimarioResponse() {
        }
        
        public cancelaCFDISectorPrimarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDISignature", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDISignatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioSIFEI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] archivoZIP;
        
        public cancelaCFDISignatureRequest() {
        }
        
        public cancelaCFDISignatureRequest(string usuarioSIFEI, string passUser, byte[] archivoZIP) {
            this.usuarioSIFEI = usuarioSIFEI;
            this.passUser = passUser;
            this.archivoZIP = archivoZIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDISignatureResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class cancelaCFDISignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelaCFDISignatureResponse() {
        }
        
        public cancelaCFDISignatureResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLProceso", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getXMLProcesoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idseguimiento;
        
        public getXMLProcesoRequest() {
        }
        
        public getXMLProcesoRequest(string rfc, string pass, long idseguimiento) {
            this.rfc = rfc;
            this.pass = pass;
            this.idseguimiento = idseguimiento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLProcesoResponse", WrapperNamespace="http://MApeados/", IsWrapped=true)]
    public partial class getXMLProcesoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MApeados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getXMLProcesoResponse() {
        }
        
        public getXMLProcesoResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SIFEIChannel : SifeiWebService.SifeiWebServiceDev.SIFEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIFEIClient : System.ServiceModel.ClientBase<SifeiWebService.SifeiWebServiceDev.SIFEI>, SifeiWebService.SifeiWebServiceDev.SIFEI {
        
        public SIFEIClient() {
        }
        
        public SIFEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIFEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIFEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIFEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse SifeiWebService.SifeiWebServiceDev.SIFEI.CambiaPassword(SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest request) {
            return base.Channel.CambiaPassword(request);
        }
        
        public bool CambiaPassword(string Usuario, string Password, string NewPassword) {
            SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest inValue = new SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.NewPassword = NewPassword;
            SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).CambiaPassword(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.CambiaPasswordAsync(SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest request) {
            return base.Channel.CambiaPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.CambiaPasswordResponse> CambiaPasswordAsync(string Usuario, string Password, string NewPassword) {
            SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest inValue = new SifeiWebService.SifeiWebServiceDev.CambiaPasswordRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.NewPassword = NewPassword;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).CambiaPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDIAndURL(SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest request) {
            return base.Channel.getCFDIAndURL(request);
        }
        
        public string[] getCFDIAndURL(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDIAndURL(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDIAndURLAsync(SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest request) {
            return base.Channel.getCFDIAndURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIAndURLResponse> getCFDIAndURLAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIAndURLRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDIAndURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getCFDIResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDI(SifeiWebService.SifeiWebServiceDev.getCFDIRequest request) {
            return base.Channel.getCFDI(request);
        }
        
        public byte[] getCFDI(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getCFDIResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDIAsync(SifeiWebService.SifeiWebServiceDev.getCFDIRequest request) {
            return base.Channel.getCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIResponse> getCFDIAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDISendPDF(SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest request) {
            return base.Channel.getCFDISendPDF(request);
        }
        
        public byte[] getCFDISendPDF(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDISendPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDISendPDFAsync(SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest request) {
            return base.Channel.getCFDISendPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISendPDFResponse> getCFDISendPDFAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDISendPDFRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDISendPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDIProcesa(SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest request) {
            return base.Channel.getCFDIProcesa(request);
        }
        
        public string[] getCFDIProcesa(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDIProcesa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDIProcesaAsync(SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest request) {
            return base.Channel.getCFDIProcesaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDIProcesaResponse> getCFDIProcesaAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDIProcesaRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDIProcesaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getCFDISignResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDISign(SifeiWebService.SifeiWebServiceDev.getCFDISignRequest request) {
            return base.Channel.getCFDISign(request);
        }
        
        public byte[] getCFDISign(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDISignRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDISignRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getCFDISignResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDISign(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISignResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getCFDISignAsync(SifeiWebService.SifeiWebServiceDev.getCFDISignRequest request) {
            return base.Channel.getCFDISignAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getCFDISignResponse> getCFDISignAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getCFDISignRequest inValue = new SifeiWebService.SifeiWebServiceDev.getCFDISignRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getCFDISignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.setCFDIResponse SifeiWebService.SifeiWebServiceDev.SIFEI.setCFDI(SifeiWebService.SifeiWebServiceDev.setCFDIRequest request) {
            return base.Channel.setCFDI(request);
        }
        
        public byte[] setCFDI(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.setCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.setCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.setCFDIResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).setCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.setCFDIResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.setCFDIAsync(SifeiWebService.SifeiWebServiceDev.setCFDIRequest request) {
            return base.Channel.setCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.setCFDIResponse> setCFDIAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.setCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.setCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).setCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getTimbreCFDI(SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest request) {
            return base.Channel.getTimbreCFDI(request);
        }
        
        public byte[] getTimbreCFDI(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getTimbreCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getTimbreCFDIAsync(SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest request) {
            return base.Channel.getTimbreCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getTimbreCFDIResponse> getTimbreCFDIAsync(string Usuario, string Password, byte[] archivoXMLZip, string Serie, string IdEquipo) {
            SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.getTimbreCFDIRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.archivoXMLZip = archivoXMLZip;
            inValue.Serie = Serie;
            inValue.IdEquipo = IdEquipo;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getTimbreCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getXMLResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getXML(SifeiWebService.SifeiWebServiceDev.getXMLRequest request) {
            return base.Channel.getXML(request);
        }
        
        public string getXML(string rfc, string pass, string hash) {
            SifeiWebService.SifeiWebServiceDev.getXMLRequest inValue = new SifeiWebService.SifeiWebServiceDev.getXMLRequest();
            inValue.rfc = rfc;
            inValue.pass = pass;
            inValue.hash = hash;
            SifeiWebService.SifeiWebServiceDev.getXMLResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getXMLAsync(SifeiWebService.SifeiWebServiceDev.getXMLRequest request) {
            return base.Channel.getXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLResponse> getXMLAsync(string rfc, string pass, string hash) {
            SifeiWebService.SifeiWebServiceDev.getXMLRequest inValue = new SifeiWebService.SifeiWebServiceDev.getXMLRequest();
            inValue.rfc = rfc;
            inValue.pass = pass;
            inValue.hash = hash;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDI(SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest request) {
            return base.Channel.cancelaCFDI(request);
        }
        
        public string cancelaCFDI(string usuarioSIFEI, string passUser, string rfc, byte[] pfx, string passPFX, string[] UUIDS) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.rfc = rfc;
            inValue.pfx = pfx;
            inValue.passPFX = passPFX;
            inValue.UUIDS = UUIDS;
            SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDIAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest request) {
            return base.Channel.cancelaCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDIResponse> cancelaCFDIAsync(string usuarioSIFEI, string passUser, string rfc, byte[] pfx, string passPFX, string[] UUIDS) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDIRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.rfc = rfc;
            inValue.pfx = pfx;
            inValue.passPFX = passPFX;
            inValue.UUIDS = UUIDS;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDISectorPrimario(SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest request) {
            return base.Channel.cancelaCFDISectorPrimario(request);
        }
        
        public string cancelaCFDISectorPrimario(string usuarioSIFEI, string passUser, string rfc, string[] UUIDS) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.rfc = rfc;
            inValue.UUIDS = UUIDS;
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDISectorPrimario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDISectorPrimarioAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest request) {
            return base.Channel.cancelaCFDISectorPrimarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioResponse> cancelaCFDISectorPrimarioAsync(string usuarioSIFEI, string passUser, string rfc, string[] UUIDS) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDISectorPrimarioRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.rfc = rfc;
            inValue.UUIDS = UUIDS;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDISectorPrimarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDISignature(SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest request) {
            return base.Channel.cancelaCFDISignature(request);
        }
        
        public string cancelaCFDISignature(string usuarioSIFEI, string passUser, byte[] archivoZIP) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.archivoZIP = archivoZIP;
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDISignature(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.cancelaCFDISignatureAsync(SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest request) {
            return base.Channel.cancelaCFDISignatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureResponse> cancelaCFDISignatureAsync(string usuarioSIFEI, string passUser, byte[] archivoZIP) {
            SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest inValue = new SifeiWebService.SifeiWebServiceDev.cancelaCFDISignatureRequest();
            inValue.usuarioSIFEI = usuarioSIFEI;
            inValue.passUser = passUser;
            inValue.archivoZIP = archivoZIP;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).cancelaCFDISignatureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse SifeiWebService.SifeiWebServiceDev.SIFEI.getXMLProceso(SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest request) {
            return base.Channel.getXMLProceso(request);
        }
        
        public string[] getXMLProceso(string rfc, string pass, long idseguimiento) {
            SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest inValue = new SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest();
            inValue.rfc = rfc;
            inValue.pass = pass;
            inValue.idseguimiento = idseguimiento;
            SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse retVal = ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getXMLProceso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse> SifeiWebService.SifeiWebServiceDev.SIFEI.getXMLProcesoAsync(SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest request) {
            return base.Channel.getXMLProcesoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SifeiWebService.SifeiWebServiceDev.getXMLProcesoResponse> getXMLProcesoAsync(string rfc, string pass, long idseguimiento) {
            SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest inValue = new SifeiWebService.SifeiWebServiceDev.getXMLProcesoRequest();
            inValue.rfc = rfc;
            inValue.pass = pass;
            inValue.idseguimiento = idseguimiento;
            return ((SifeiWebService.SifeiWebServiceDev.SIFEI)(this)).getXMLProcesoAsync(inValue);
        }
    }
}
